### ISSUE TITLE
spary cosmetic

### ISSUE THREAD

**Issue by magicelk235** [HibiscusMC/HMCCosmetics#101]
### Feature Description

when you shift + f it put a n item for X time

### Implementation Description

for spray add
time: (the remaining time in ticks, by default 60t=3s)
spray: (the item that will show up, by default the menu item)

**Comment by LoJoSho** [comment]
So it just drops an item you can't pickup?

**Comment by Craftinators** [comment]
@magicelk235 Confused as to what exactly you are requesting?

**Comment by magicelk235** [comment]
It places the item in entity like item frame or display item or armor stand and disappear after X time

**Comment by Craftinators** [comment]
@magicelk235 Do you mean something similar to what Hypixel has?

Like this below, but make it temporary as the spray will disappear after a certain amount of time?
![Hypixel Spray](https://user-images.githubusercontent.com/38141658/235412528-d7a77606-5bfc-4a00-b2bc-be90a9f84084.png)

**Comment by Craftinators** [comment]
@LoJoSho Would you mind assigning me to this issue?

**Comment by Craftinators** [comment]
If you can explain what it is you want exactly, this issue will be reopened

**Comment by Brickgard** [comment]
If you'll allow me to take a crack at re-pitching this:

Sprays are a custom, cosmetic art piece players could temporarily apply to the game world.
Traditionally, these are usually something like selecting from a prepared list of (usually unlockable, such as via permission) map arts server-side.
While some systems allow users to upload their own spray, most servers that value cosmetics prefer to have a controlled, prepared list of imported graphics.
So yes, similar to the Hypixel implementation of the idea.

Ultimately, my preferred implementation/proposal would be:
A new cosmetic type, "Sprays", with a new category in the `/cosmetic` menu.  However, instead of using custom models displayed on a player, instead it is a prepared 256x256 `.png` shown as an in-game map art for a configurable, temporary amount of time.
A configurable sound with pitch on spray would be nice (traditionally a silverfish hiss for a spraycan-effect).
Having the trigger configurable between a few options may be valuable too, such as Shift+F vs Double-F and of course `/spray`.
As a stretch goal, the optional ability to control where sprays are placed, such as through a block whitelist or only triggering it on empty item frames would allow server-controlled map compatibility, such as in minigames (allowing designated spray spots on maps).

I believe this would be a huge value-add to HMCCosmetics (and really round out the cosmetic offerings), and truth be told I was honestly surprised when I learned it wasn't a current feature.  I hope addressing this already-closed feature is alright, but I figured it'd be better than opening a new one (which is what brought me here today).
