### ISSUE TITLE
[FEATURE] NBT Tag Support For Armor

### ISSUE THREAD

**Issue by Lamus1** [HibiscusMC/HMCCosmetics#33]
### I have checked that...

- [x] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Players should be able to specify NBT Tags for the items worn on the player, similar to how they can decide the ID for the CustomModelTag in the config menu. This feature can be used to make armor display custom appearance when worn on the player, and works alongside Optifine. It can also open the door to other customization effects. It could be entered as such:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/109258623/187315179-6168eb1c-3be9-421a-af59-3be09d56a0ef.png">

**Comment by LoJoSho** [comment]
On my radar, but low priority for now.

**Comment by LoJoSho** [comment]
I have committed something similar to what this issue is talking about. However, I am unsure how Optifine handles nbt data when it checks. I have looked into https://optifine.readthedocs.io/syntax.html#nbt however, I have not found the answer I am looking for. If someone has the solution that this needs, please feel free to comment.
