### ISSUE TITLE
[FEATURE] New API methods and other feature ideas

### ISSUE THREAD

**Issue by Boy0000** [HibiscusMC/HMCCosmetics#54]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Think it would be nice to be able to set multiple wardrobes in the config. Probably based on an ID
Temporary wardrobes would be rather simple to implement then in theory
WardrobeSettings would also need to be a property of each Wardrobe rather than a global one

```java
WardrobeSettings.setApplyCosmeticsOnClose(boolean) //Nice for having previews of cosmetics
WardrobeSettings.allowedUsers(Set<CosmeticUser>) // Could be good for making private wardrobes for houses / guilds

```

**Comment by LoJoSho** [comment]
This is definitely something that can be looked into!

**Comment by LoJoSho** [comment]
#56 created the getDefaultMenu method

**Comment by Boy0000** [comment]
Temporary wardrobes are also doable now via api methods

**Comment by LoJoSho** [comment]
This issue is mostly complete and can now be done with most things. With #111, it will also formally add trying cosmetics and multiple cosmetics. I decided against having sets of players, as that's just odd for the plugin to do. Instead, HMCC will stick with permissions. 

As always, third-party plugins can create new wardrobes and limit access to it based on PlayerWardrobeEnterEvent
