### ISSUE TITLE
[BUG] armors bugging when playing emote / getting kicked due to "Cannot interact with self!"

### ISSUE THREAD

**Issue by ghost** [HibiscusMC/HMCCosmetics#76]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

https://www.youtube.com/watch?v=HLp1usiabvQ

### Steps to reproduce

i get kicked if i click on air(or armorstands idk) (doesnt matter left or right click) while playing an emote

### Plugin Version

2.2.4(self build)

### Server Version

git-Paper-307 (MC: 1.19.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by LoJoSho** [comment]
This is a known issue and has been discussed on Discord on solutions. I can not personally replicate it, but many other people have had this issue. It happens because we sent a client packet that sends the player to a different location than where the server thinks they are and so when they interact while emoting, it can kicks them. 

This should fix it, but apparently, it isn't. https://github.com/HibiscusMC/HMCCosmetics/blob/remapped/common/src/main/java/com/hibiscusmc/hmccosmetics/listener/PlayerGameListener.java#L388-L407

**Comment by ghost** [comment]
cancelling PacketType.Play.Client.USE_ENTITY instead of PacketType.Play.Client.ARM_ANIMATION fixes the problem

**Comment by LoJoSho** [comment]
Tested and appears to work, https://github.com/HibiscusMC/HMCCosmetics/commit/9f6c7db8fd9a50df8774c995f7eba4ca5fe19e81

Ty for your information on the matter, I never would have guessed it was that packet!
