### ISSUE TITLE
[FEATURE] Placeholder to state whether you a certain type of cosmetic on

### ISSUE THREAD

**Issue by BendersRepublic** [HibiscusMC/HMCCosmetics#96]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

`%hmccosmetics_current_<type>%` that's it. 
ex: `%hmccosmetics_current_backpack% = true/false` 

I have certain systems that use this type of placeholder to determine for example if you're wearing a backpack or not. Which allows our players to only use backpack storage function if they have the cosmetic equipped

**Comment by LoJoSho** [comment]
This actually already exists under equipped, however, the documentation was a bit out of date. This has been fixed in https://github.com/HibiscusMC/docs/commit/cfd6f896c2091bc1c169697e75e1ef7dd1559804. The docs have now been updated and you can find it [here](https://docs.hibiscusmc.com/hmccosmetics%20remapped/PlaceholderAPI/).
